### ISSUE TITLE
[bug] The website fails

### ISSUE THREAD

**Issue by monchin** [laike9m/Python-Type-Challenges#126]
On the [website](https://python-type-challenges.zeabur.app/basic/any), no matter what you input, when you click `run` button, it'll show
```
❌ Challenge failed 😢
Error:
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in _run_code
File "/app/.venv/lib/python3.13/site-packages/nodeenv.py", line 26, in
import pipes
ModuleNotFoundError: No module named 'pipes'
Traceback (most recent call last):
File "/app/.venv/bin/pyright", line 8, in
sys.exit(entrypoint())
~~~~~~~~~~^^
File "/app/.venv/lib/python3.13/site-packages/pyright/cli.py", line 34, in entrypoint
sys.exit(main(sys.argv[1:]))
~~~~^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.13/site-packages/pyright/cli.py", line 19, in main
return run(*args, **kwargs).returncode
~~~^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.13/site-packages/pyright/cli.py", line 25, in run
pkg_dir = install_pyright(args, quiet=None)
File "/app/.venv/lib/python3.13/site-packages/pyright/_utils.py", line 64, in install_pyright
node.run(
~~~~~~~~^
'npm',
^^^^^^
...<5 lines>...
stderr=subprocess.PIPE if silent else sys.stderr,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
^
File "/app/.venv/lib/python3.13/site-packages/pyright/node.py", line 105, in run
binary = _ensure_available(target)
File "/app/.venv/lib/python3.13/site-packages/pyright/node.py", line 38, in _ensure_available
return Binary(path=_ensure_node_env(target), strategy=Strategy.NODEENV)
~~~~~~~~~~~~~~~~^^^^^^^^
File "/app/.venv/lib/python3.13/site-packages/pyright/node.py", line 65, in _ensure_node_env
_install_node_env()
~~~~~~~~~~~~~~~~~^^
File "/app/.venv/lib/python3.13/site-packages/pyright/node.py", line 98, in _install_node_env
subprocess.run(args, check=True)
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/subprocess.py", line 577, in run
raise CalledProcessError(retcode, process.args,
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/app/.venv/bin/python', '-m', 'nodeenv', '/root/.cache/pyright-python/nodeenv']' returned non-zero exit status 1.
```

**Comment by laike9m** [comment]
Thanks for reporting. Looks like this is an issue with Python 3.13, will fix it
